apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service-mysql
  name: user-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service-mysql
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: user-service-mysql
    spec:
      containers:
        - name: user-service-mysql
          image: mysql:8.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: user_service
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-data-user
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data-user
          persistentVolumeClaim:
            claimName: mysql-pvc-user