apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    io.kompose.service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - name: user-service
          image: trainingtexas/user-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: app_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://user-service-mysql:3306/user_service
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "200m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
