apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-network
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - image: trainingtexas/user-service:latest
          name: user-service-container
          ports:
            - containerPort: 8085
              protocol: TCP
      restartPolicy: Always
