name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests with Maven
        run: mvn test

  sonarcloud-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run SonarCloud analysis
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=AndreiPieleanu_user-service \
            -Dsonar.organization=andreipieleanu \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  docker:
    runs-on: ubuntu-latest
    needs: sonarcloud-check
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          docker --version
      - name: Build with Maven (again, if necessary)
        run: mvn -B package --file pom.xml
      - name: Build Docker image
        run: |
          docker build -t user-service:latest .
      - name: Tag Docker image
        run: |
          docker tag user-service:latest trainingtexas/user-service:latest
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          docker push trainingtexas/user-service:latest